use_frameworks!

platform :ios, '10.0'

target 'PrivateHelloWorld_Example' do
  pod 'PrivateHelloWorld', :path => '../'

  target 'PrivateHelloWorld_Tests' do
    inherit! :search_paths

    
  end
end
